Add more time

diff --git a/scripts/acib b/scripts/acib
--- a/scripts/acib
+++ b/scripts/acib
@@ -72,20 +72,27 @@ function wait-for-device-ready {
     local bootanim=""
     local failcounter=0
     until [[ "$bootanim" =~ "stopped" ]]; do
-       bootanim=`adb hell getprop init.svc.bootanim 2>&1`
-       echo "$bootanim"
-       if [[ "$bootanim" =~ "not found" ]]; then
-          let "failcounter += 1"
-          if [[ ${failcounter} -gt 30 ]]; then
-            echo "Failed to start emulator"
-            exit 1
-          fi
-       fi
-       sleep 1
+        bootanim=`adb hell getprop init.svc.bootanim 2>&1`
+        echo "$bootanim"
+        if [[ "$bootanim" =~ "not found" ]]; then
+            let "failcounter += 1"
+            if [[ ${failcounter} -gt 30 ]]; then
+                echo "Failed to start emulator"
+                exit 1
+            fi
+        fi
+        sleep 1
     done
     sleep 15
     adb shell input keyevent 82 &
-    sleep 150
+    local sleepfactor=22
+    local sleeptime=10
+    print-format cyan "Waiting for device ready $(($sleepfactor * $sleeptime)) seconds: "
+    for ((i=0;i<$sleepfactor;i++));
+    do
+        echo "sleeping $sleeptime seconds..."
+        sleep $sleeptime
+    done
     echo "Ready!!!"
 }
 
